#pragma once
#define _CRT_SECURE_NO_WARNINGS

#pragma comment(lib, "OpenGL32.Lib")
#pragma comment(lib, "glew32.lib")
#pragma warning(disable: 4711 4710 4100)	
#pragma comment(lib, "freeglut.lib")

#include <glm/glm.hpp>
#include <glm/ext.hpp>
#include <glm/gtx/string_cast.hpp> 
#include <glm/gtc/type_ptr.hpp> 
#include <GL/glew.h>
#include <gl/freeglut.h>
#include <gl/freeglut_ext.h>

#include <thread>
#include <iostream>
#include <algorithm>
#include <vector>
#include <memory>
#include <execution>
#include <atomic>
#include <span>
using std::jthread;
using std::thread;
using std::vector;
using std::unique_ptr;
using std::make_unique;
#include <string>
using std::string;
using std::wstring;
#include <string_view>
using std::string_view;
using std::wstring_view;
#include <cmath>
#include <cassert>
#include <map>
#include <algorithm>
#include <bitset>
#include <unordered_map>
#include <optional>
#include <utility>
#include <variant>
#include <array>
#include <functional>
#include <any>
using std::bind;
using std::any;
using std::function;
using std::array;
using std::variant;
using std::get;
using std::optional;
using std::unordered_map;
using std::bitset;
using std::map;
using std::make_pair;
using std::shared_ptr;
using std::weak_ptr;
using std::unordered_multimap;
using std::multimap;
#include <sstream>
using std::stringstream;
#include <fstream>
using std::ifstream;
using std::ofstream;
#include <coroutine>
#include <list>
#include <fstream>
#include <chrono>
#include <filesystem>
#include <cmath>
#include <ranges>
#include <format>
namespace fs = std::filesystem;
#include <concepts>
#include <type_traits>
#include <typeinfo>
#include <typeindex>
#include <bitset>
#include <future>
#include <cfloat>
#include <span>
#include <random>
#include <semaphore>
#include <compare>
#include <set>
#include <variant>
using std::span;
using std::make_shared;
using std::enable_shared_from_this;
using std::wofstream;
using std::wifstream;
using std::list;
#include <initializer_list>
using std::initializer_list;
using std::pair;

#include "YGLMath.hpp"